version: "3"
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
  web:
    environment: 
      HUB_URL: http://chrome:4444/wd/hub
    depends_on:
      - chrome
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
  selenium-hub:
    image: selenium/hub
    environment:
      - GRID_TIMEOUT=120
      - GRID_MAX_SESSION=200
      - GRID_NEW_SESSION_WAIT_TIMEOUT=-1
      - GRID_BROWSER_TIMEOUT=120
    ports:
      - "4444:4444"
  chrome:
    image: selenium/standalone-chrome
    links:
      - selenium-hub:hub
    volumes:
    - /dev/shm:/dev/shm
    privileged: true
